### ISSUE TITLE
Change selected card color in browser

### ISSUE THREAD

**Issue by arisp99** [AnKing-Memberships/AnkiRecolor#22]
#### Checklist

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

```
2.1.55 Qt 6
```
#### Problem case

Regardless of the theme used (e.g., Nord, Anki, custom theme, etc.), it does not currently seem possible to customize the color of a selected card in browser mode. The color defaults to light green, as shown below:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/19840652/210310281-9feae98e-121b-487d-baa0-924b8fda7115.png">

#### Solution

Ideally, it would be possible to customize the color of a selected card in the settings for this addon.

**Comment by BlueGreenMagick** [comment]
Let's discuss this in #24
