### ISSUE TITLE
Background button color

### ISSUE THREAD

**Issue by talkael** [AnKing-Memberships/AnkiRecolor#23]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ yes] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ yes] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

Latest version

#### Problem case

Using the add on combins button background of anki with the button backfground fields of the anking note type (such as FA, BB, Pathoma) which makes it an issue when wanting a regular white background for the regular buttons but keeping it dark for those fiels

#### Solution

Either provide a separate feature or prevent the add on from overriding the note type.

**Comment by BlueGreenMagick** [comment]
Should be fixed after uploading the fixed version to ankiweb (Should take < 1week)
