### ISSUE TITLE
Recolor 04/24/2023 update error on Windows 2.1.49 dc80804a

### ISSUE THREAD

**Issue by thesomkheha** [AnKing-Memberships/AnkiRecolor#30]
#### Problem description

No idea what happened, it was working fine for a bit after the update. It then suddenly stopped working when I restarted today. The ReColor toolbar up top is gone and the theme reverted back to default, original Anki grey. I cannot update my Anki to newer releases due to the conflict with other add-ons.

#### Checklist
 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
When loading '⁨ReColor⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 230, in loadAddons
  File "C:\Users\San\AppData\Roaming\Anki2\addons21\688199788\__init__.py", line 7, in <module>
    from . import colors
  File "C:\Users\San\AppData\Roaming\Anki2\addons21\688199788\colors.py", line 10, in <module>
    from anki.utils import is_mac
ImportError: cannot import name 'is_mac' from 'anki.utils' (C:\Program Files\Anki\anki\utils.pyc)
```

**Comment by AnKingMed** [comment]
Just released the old version that should resolve this
